project_id = "xvopwjwgvriisizysbkf"

[functions.export-company-data]
verify_jwt = false

[functions.ncm-lookup]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.nuvem-fiscal]
verify_jwt = false
